defmodule Chopaat.MobApp do
  @moduledoc """
  On-device entry point (the `mix mob.adopt` thin-client shape, hand-written
  because the guarded adopt tasks refuse non-Phoenix projects by policy —
  see `decisions/2026-08-30-mob-adoption.md`). `src/chopaat.erl` calls
  `start/0` (generated by `use Mob.App`), which boots the Mob runtime and
  then `on_start/0`.

  Mix config files are not loaded on device, so runtime config the plugin
  needs (`:mob_scene3d` asset root) is set here; `config/config.exs`
  carries the same values for host-side tests.
  """

  use Mob.App

  @impl Mob.App
  def navigation(_platform) do
    stack(:main, root: Chopaat.Screens.MenuScreen)
  end

  @impl Mob.App
  def on_start do
    Application.put_env(:mob_scene3d, :asset_root, {:chopaat, "priv/assets"})

    Mob.DNS.configure_pure_beam()
    Mob.Screen.start_root(Chopaat.Screens.MenuScreen)

    Mob.Dist.ensure_started(
      node: :"chopaat@127.0.0.1",
      cookie: :mob_secret
    )
  end
end
