// Generated by mob_dev (MobDev.NativeBuild) — do not edit.
// Calls each activated plugin's bridge-class register() at startup, then
// hands the Activity to any bridge implementing MobActivityAware and records
// any bridge implementing MobPermissionProvider; also registers the plugins'
// ui_components Compose factories with the app's MobNativeViewRegistry.
// Invoked from MainActivity.onCreate as registerAll(this), before
// setContent renders anything.
package io.mob.plugin

import android.app.Activity

object MobPluginBootstrap {
    private val permissionProviders = mutableListOf<MobPermissionProvider>()

    @JvmStatic
    fun registerAll(activity: Activity) {
        io.mob.scene3d.MobScene3dBridge.register()
        handOff(io.mob.scene3d.MobScene3dBridge, activity)
        collectPermissionProvider(io.mob.scene3d.MobScene3dBridge)
        registerUiComponents()
    }

    // Returns the first plugin-supplied Android permission mapping for `cap`,
    // or null if no activated plugin provides this capability. Core
    // MobBridge.request_permission consults this in its `else` branch.
    @JvmStatic
    fun permissionsFor(cap: String): Array<String>? {
        for (provider in permissionProviders) {
            val perms = provider.permissionsFor(cap)
            if (perms != null) return perms
        }
        return null
    }

    // Hands the Activity to a bridge that opts in via MobActivityAware.
    private fun handOff(bridge: Any, activity: Activity) {
        (bridge as? MobActivityAware)?.setActivity(activity)
    }

    // Records a bridge that opts in via MobPermissionProvider so core
    // MobBridge.request_permission can fall through to it for a capability
    // core no longer knows about.
    private fun collectPermissionProvider(bridge: Any) {
        (bridge as? MobPermissionProvider)?.let {
            if (!permissionProviders.contains(it)) permissionProviders.add(it)
        }
    }

    // Registers the activated plugins' ui_components Compose factories
    // with the app's MobNativeViewRegistry (generated from each plugin
    // manifest — the Android analog of iOS's mob_register_plugins()).
    private fun registerUiComponents() {
        // mob_scene3d: Mob_Scene3d_Viewport
        com.genericjam.chopaat.MobNativeViewRegistry.register("Mob_Scene3d_Viewport") { props, _ ->
            io.mob.scene3d.MobScene3dViewport(props)
        }
    }
}
